/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OAccount {
  accessKey: string;
  bucketName: string;
  cdnUrl?: string | null;
  secretKey: string;
  serviceUrl: string;
}
