/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OFile {
  S3Url?: string | null;
  fileName?: string | null;
  key?: string | null;
  mimeType?: string | null;
}
